name: Lint - EditorConfig

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: editorconfig-checker/action-editorconfig-checker@v2

      - name: Run editorconfig-checker
        run: editorconfig-checker
